routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', fn () => view('welcome'));

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    Route::get('/social-posts', 'SocialPostsController@index')->name('social-posts.index');
    Route::get('/social-posts/create', 'SocialPostsController@create')->name('social-posts.create');
    Route::post('/social-posts', 'SocialPostsController@store')->name('social-posts.store');
    Route::get('/social-posts/{socialPost}/edit', 'SocialPostsController@edit')->name('social-posts.edit');
    Route::patch('/social-posts/{socialPost}', 'SocialPostsController@update')->name('social-posts.update');
    Route::delete('/social-posts/{socialPost}', 'SocialPostsController@destroy')->name('social-posts.destroy');
});

app/SocialPost.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SocialPost extends Model
{
    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The author associated to this post.
     */
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getAvatarAttribute()
    {
        return "https://api.adorable.io/avatars/128/{$this->attributes['email']}";
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SocialPostsController.php
<?php

namespace App\Http\Controllers;

use App\SocialPost;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;

class SocialPostsController extends Controller
{
    public function index()
    {
        return view('social-posts.index', [
            'socialPosts' => SocialPost::with('author')
                ->where('content', 'like', '%' . request('search') . '%')
                ->orderByDesc('updated_at')
                ->paginate()
        ]);
    }

    public function create()
    {
        return view('social-posts.create');
    }

    public function store(Request $request)
    {
        $attributes = $request->validate([
            'content' => ['required', 'string'],
            'channel' => ['required', Rule::in('Facebook', 'Instagram', 'Linked In', 'Youtube')],
            'status' => ['required', Rule::in('Draft', 'For Approval', 'Scheduled', 'Published', 'Declined')],
            'image' => ['nullable', 'image'],
        ]);

        if ($request->hasFile('image')) {
            $attributes['image'] = Storage::url(
                $request->file('image')->store('uploads', 'public')
            );
        }

        $socialPost = SocialPost::create(array_merge($attributes, [
            'user_id' => auth()->id()
        ]));

        return redirect()
            ->route('social-posts.index')
            ->with(compact('socialPost'));
    }

    public function edit(SocialPost $socialPost)
    {
        return view('social-posts.edit', compact('socialPost'));
    }

    public function update(Request $request, SocialPost $socialPost)
    {
        $attributes = $request->validate([
            'content' => ['required', 'string'],
            'channel' => ['required', Rule::in('Facebook', 'Instagram', 'Linked In', 'Youtube')],
            'status' => ['required', Rule::in('Draft', 'For Approval', 'Scheduled', 'Published', 'Declined')],
            'image' => ['nullable', 'image'],
        ]);

        if ($request->hasFile('image')) {
            $attributes['image'] = Storage::url(
                $request->file('image')->store('uploads', 'public')
            );
        }

        $socialPost->update($attributes);

        return redirect()
            ->route('social-posts.index')
            ->with(compact('socialPost'));
    }

    public function destroy(SocialPost $socialPost)
    {
        $socialPost->delete();

        return redirect()->route('social-posts.index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="max-w-screen-xl mx-auto px-6">
    <div class="font-medium text-lg">Dashboard</div>
    <div class="mt-4">You are logged in!</div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">

    <!-- Styles -->
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
</head>
<body class="font-sans antialiased {{ $bodyClass ?? 'bg-gray-200 bg-opacity-50' }}">
    <div id="app">
        <div class="h-16 bg-white border-b flex items-center">
            <div class="w-full max-w-screen-xl mx-auto px-6 flex items-center justify-between">
                <div class="inline-flex items-center">
                    <a href="{{ url('/') }}" class="font-semibold">Surefire Clone</a>
                </div>

                @auth
                <div class="inline-flex items-center space-x-8">
                    <a class="font-medium text-gray-400 hover:text-gray-700" href="#">Leads</a>
                    <a class="font-medium text-gray-400 hover:text-gray-700" href="#">Reputation</a>
                    <a class="font-medium {{ Route::is('social-posts*') ? 'text-current' : 'text-gray-400' }} hover:text-gray-700" href="{{ route('social-posts.index') }}">Social</a>
                </div>
                @endauth

                <div class="inline-flex items-center space-x-4">
                    @guest
                        <a href="{{ route('login') }}">Login</a>
                        <a href="{{ route('register') }}">Register</a>
                    @else
                        <div class="relative group">
                            <a href="" class="flex items-center">
                                <img class="w-6 h-6 rounded-full" src="{{ Auth::user()->avatar }}" alt="">
                                <span class="ml-2 font-medium text-gray-700">{{ Auth::user()->name }}</span>
                            </a>
                            <div class="invisible group-hover:visible absolute right-0 w-56 pt-2">
                                <div class="rounded-lg shadow-lg">
                                    <div class="bg-white rounded-lg shadow-xs">
                                        <div class="py-1">
                                            <a href="" class="block w-full px-4 py-2 text-gray-700 text-sm hover:bg-gray-200">Profile</a>
                                            <a href="" class="block w-full px-4 py-2 text-gray-700 text-sm hover:bg-gray-200">Change Password</a>
                                            <hr class="my-1">
                                            <a href="" class="block w-full px-4 py-2 text-gray-700 text-sm hover:bg-gray-200">Contact Support</a>
                                            <a href="#" onclick="document.getElementById('logoutForm').submit()" class="block w-full px-4 py-2 text-gray-700 text-sm hover:bg-gray-200">Logout</a>
                                            <form id="logoutForm" class="hidden" action="{{ route('logout') }}" method="POST">
                                                @csrf
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endguest
                </div>
            </div>
        </div>

        <main class="py-8">
            @yield('content')
        </main>
    </div>

    @stack('scripts')
</body>
</html>

resources/views/social-posts/create.blade.php
@extends('layouts.app', ['bodyClass' => 'bg-white'])

@section('content')
<div class="max-w-screen-md mx-auto px-6">
    <h1 class="font-medium text-lg">Write a social post</h1>
    <p class="text-gray-500 mt-1">Start writing your social post by providing the details below.</p>
    <hr class="my-8 border-gray-200">
    <form action="{{ route('social-posts.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        @include('social-posts.form', ['socialPost' => new App\SocialPost])
    </form>
</div>
@endsection

resources/views/social-posts/edit.blade.php
@extends('layouts.app', ['bodyClass' => 'bg-white'])

@section('content')
<div class="max-w-screen-md mx-auto px-6">
    <h1 class="font-medium text-lg">Edit this post</h1>
    <p class="text-gray-500 mt-1">You may modify any information for this social post as long as the status is neither scheduled nor published.</p>
    <hr class="my-8 border-gray-200">
    <form action="{{ route('social-posts.update', $socialPost) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PATCH')

        @include('social-posts.form')
    </form>
</div>
@endsection

resources/views/social-posts/form.blade.php
<div class="flex flex-wrap">
    <div class="w-full md:w-1/3 ">
        <label for="content" class="inline-block font-medium text-gray-600 mb-1">Content</label>
    </div>
    <div class="w-full md:w-2/3">
        <textarea
            class="form-input block w-full"
            id="content"
            placeholder="Write something nice"
            name="content"
            rows="7"
        >{{ old('content', $socialPost->content) }}</textarea>

        <p class="text-gray-500 mt-2">
            For twitter posts, you may only post up to 255 characters.
        </p>

        @error('content')
            <p class="text-red-500 text-sm mt-2">
                {{ $message }}
            </p>
        @enderror
    </div>
</div>

<hr class="my-8 border-gray-200">

<div class="flex flex-wrap">
    <div class="w-full md:w-1/3 ">
        <label for="channel" class="inline-block font-medium text-gray-600 mb-1">Channel</label>
    </div>
    <div class="w-full md:w-2/3">
        <select id="channel" name="channel" class="form-select block w-full max-w-sm">
            <option {{ old('channel', $socialPost->channel) === 'Facebook' ? 'selected' : '' }}>Facebook</option>
            <option {{ old('channel', $socialPost->channel) === 'Instagram' ? 'selected' : '' }}>Instagram</option>
            <option {{ old('channel', $socialPost->channel) === 'Linked In' ? 'selected' : '' }}>Linked In</option>
            <option {{ old('channel', $socialPost->channel) === 'Youtube' ? 'selected' : '' }}>Youtube</option>
        </select>

        <p class="text-gray-500 mt-2">
            You may add more channels in the <a href="#" class="text-indigo-600">settings page</a>.
        </p>

        @error('channel')
            <p class="text-red-500 text-sm mt-2">
                {{ $message }}
            </p>
        @enderror
    </div>
</div>

<hr class="my-8 border-gray-200">

<div class="flex flex-wrap">
    <div class="w-full md:w-1/3">
        <label for="status" class="inline-block font-medium text-gray-600 mb-1">Status</label>
    </div>
    <div class="w-full md:w-2/3">
        <select id="status" name="status" class="form-select block w-full max-w-sm">
            <option {{ old('status', $socialPost->status) === 'Draft' ? 'selected' : '' }}>Draft</option>
            <option {{ old('status', $socialPost->status) === 'For Approval' ? 'selected' : '' }}>For Approval</option>
            <option {{ old('status', $socialPost->status) === 'Scheduled' ? 'selected' : '' }}>Scheduled</option>
            <option {{ old('status', $socialPost->status) === 'Published' ? 'selected' : '' }}>Published</option>
            <option {{ old('status', $socialPost->status) === 'Declined' ? 'selected' : '' }}>Declined</option>
        </select>

        @error('status')
            <p class="text-red-500 text-sm mt-2">
                {{ $message }}
            </p>
        @enderror
    </div>
</div>

<hr class="my-8 border-gray-200">

<div class="flex flex-wrap">
    <div class="w-full md:w-1/3">
        <label for="image" class="inline-block font-medium text-gray-600 mb-1">Image</label>
    </div>
    <div class="w-full md:w-2/3">
        @if($socialPost->image)
            <img class="w-full max-w-sm rounded object-fit mb-4" src="{{ $socialPost->image }}" alt="">
        @endif

        <button
            @click.prevent="$refs.fileInput.click()"
            class="px-4 py-2 text-gray-700 border rounded-lg inline-flex items-center hover:bg-gray-100 focus:outline-none focus:shadow-outline-blue focus:border-blue-300"
        >
            <svg class="w-5 h-5 text-gray-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
            <span class="ml-2 font-medium" ref="fileLabel">Upload photo</span>
        </button>
        <input
            @change="e => $refs.fileLabel.innerHTML = e.target.files[0].name"
            accept="image/*"
            class="hidden"
            name="image"
            ref="fileInput"
            type="file"
        >

        @error('image')
            <p class="text-red-500 text-sm mt-2">
                {{ $message }}
            </p>
        @enderror
    </div>
</div>

<hr class="my-8 border-gray-200">

<div class="text-right space-x-2">
    <a href="{{ route('social-posts.index') }}" class="inline-flex items-center px-4 py-2 border font-medium rounded-lg focus:outline-none focus:border-blue-300 focus:shadow-outline-blue">Cancel</a>
    <button type="submit" class="inline-flex items-center px-4 py-2 border border-indigo-600 font-medium bg-indigo-600 text-white rounded-lg focus:outline-none focus:shadow-outline-blue">Save</button>
</div>

resources/views/social-posts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="max-w-screen-xl mx-auto px-6">
    <div class="flex justify-between">
        <div class="flex items-center">
            <h1 class="font-medium text-lg">Social Posts</h1>
            <form class="ml-4">
                <div class="relative w-56">
                    <input name="search" value="{{ request('search') }}" class="form-input pr-10 block w-full" type="text" placeholder="Search">
                    <div class="pointer-events-none px-3 absolute right-0 inset-y-0 flex items-center">
                        <svg class="w-5 h-5 text-gray-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                    </div>
                </div>
            </form>
        </div>
        <div class="flex items-center">
            <a href="{{ route('social-posts.create') }}" class="inline-flex items-center px-4 py-2 bg-indigo-600 font-medium text-white rounded-lg focus:shadow-outline">Create New</a>
        </div>
    </div>

    <div class="inline-block bg-white min-w-full rounded-lg overflow-hidden shadow mt-6">
        <table class="min-w-full">
            <thead>
                <tr class="border-b border-gray-200 bg-gray-50">
                    <th width="1%" class="pl-6 pr-3 py-3 medium text-left text-sm text-gray-600">
                        <input type="checkbox" class="form-checkbox">
                    </th>
                    <th width="25%" class="px-6 py-4 font-medium text-left text-sm text-gray-600">Content</th>
                    <th width="10%" class="px-6 py-4 font-medium text-left text-sm text-gray-600">Author</th>
                    <th width="1%" class="px-6 py-4 font-medium text-left text-sm text-gray-600">Status</th>
                    <th width="1%" class="px-6 py-4 font-medium text-left text-sm text-gray-600">Last Updated</th>
                </tr>
            </thead>
            <tbody>
                @foreach($socialPosts as $socialPost)
                <tr class="border-b border-gray-200 group hover:bg-gray-50 {{ $socialPost->is(session('socialPost')) ? 'bg-blue-50' : '' }}">
                    <td class="pl-6 pr-3 text-sm">
                        <input type="checkbox" class="form-checkbox">
                    </td>
                    <td class="px-6 py-4 text-sm">
                        <div class="flex">
                            <div class="flex-shrink-0">
                                <img class="w-10 h-8 rounded object-cover" src="{{ $socialPost->image }}" alt="">
                            </div>
                            <div class="flex-1 ml-4">
                                <div>{{ Str::limit($socialPost->content, 100) }}</div>
                                <div class="flex items-center space-x-4 mt-2">
                                    <span class="inline-flex items-center">
                                        <img class="w-4 h-4" src="{{ asset('img/' . Str::slug($socialPost->channel, '-') . '.svg') }}" alt="">
                                        <span class="ml-2">{{ $socialPost->channel }}</span>
                                    </span>
                                    <a href="{{ route('social-posts.edit', $socialPost) }}" class="invisible group-hover:visible font-medium">Edit</a>
                                    <a href="{{ route('social-posts.destroy', $socialPost) }}" class="invisible group-hover:visible font-medium js-confirm-delete">Delete</a>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td class="px-6 py-4 text-sm whitespace-no-wrap">
                        <div class="flex items-center">
                            <img class="w-8 h-8 rounded-full" src="{{ $socialPost->author->avatar }}" alt="">
                            <div class="ml-4">
                                <div>{{ $socialPost->author->name }}</div>
                                <div class="text-gray-500">{{ $socialPost->author->email }}</div>
                            </div>
                        </div>
                    </td>
                    <td class="px-6 py-4 text-sm whitespace-no-wrap">
                        @include('social-posts.statuses.' . Str::slug($socialPost->status, '-'))
                    </td>
                    <td class="px-6 py-4 text-sm whitespace-no-wrap">
                        <span class="text-gray-700">{{ $socialPost->updated_at->diffForHumans() }}</span>
                    </td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr class="border-t">
                    <td colspan="5" class="px-6 py-4">
                        <div class="flex items-center justify-between">
                            <div class="text-sm text-gray-700">Showing {{ $socialPosts->firstItem() }} to {{ $socialPosts->lastItem() }} of {{ $socialPosts->total() }} items</div>
                            <div>
                                {{ $socialPosts->withQueryString()->links('vendor.pagination.simple-default') }}
                            </div>
                        </div>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
@endsection

@push('scripts')
<form id="deleteForm" method="POST">
    @csrf
    @method('DELETE')
</form>

<script>
    (function() {
        document.addEventListener('click', function ($event) {
            if ($event.target.className.includes('js-confirm-delete')) {
                $event.preventDefault();
                if (window.confirm('Are you really really sure?')) {
                    let deleteForm = document.getElementById('deleteForm')
                    deleteForm.setAttribute('action', $event.target.getAttribute('href'))
                    deleteForm.submit()
                }
            }
        });
    })()
</script>
@endpush

resources/views/social-posts/statuses/declined.blade.php
<span class="inline-flex items-center px-2 py-1 rounded-lg bg-red-100">
    <span class="w-2 h-2 rounded-full bg-red-400"></span>
    <span class="ml-2 text-xs uppercase font-medium text-red-600">{{ $socialPost->status }}</span>
</span>

resources/views/social-posts/statuses/draft.blade.php
<span class="inline-flex items-center px-2 py-1 rounded-lg bg-gray-100">
    <span class="w-2 h-2 rounded-full bg-gray-400"></span>
    <span class="ml-2 text-xs uppercase font-medium text-gray-600">{{ $socialPost->status }}</span>
</span>

resources/views/social-posts/statuses/for-approval.blade.php
<span class="inline-flex items-center px-2 py-1 rounded-lg bg-orange-100">
    <span class="w-2 h-2 rounded-full bg-orange-400"></span>
    <span class="ml-2 text-xs uppercase font-medium text-orange-600">{{ $socialPost->status }}</span>
</span>

resources/views/social-posts/statuses/published.blade.php
<span class="inline-flex items-center px-2 py-1 rounded-lg bg-green-100">
    <span class="w-2 h-2 rounded-full bg-green-400"></span>
    <span class="ml-2 text-xs uppercase font-medium text-green-600">{{ $socialPost->status }}</span>
</span>

resources/views/social-posts/statuses/scheduled.blade.php
<span class="inline-flex items-center px-2 py-1 rounded-lg bg-blue-100">
    <span class="w-2 h-2 rounded-full bg-blue-400"></span>
    <span class="ml-2 text-xs uppercase font-medium text-blue-600">{{ $socialPost->status }}</span>
</span>